import type { Drop, Product } from "./types";

function escapeXml(input: string): string {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function hueFrom(input: string): number {
  let hash = 0;
  for (const char of input) hash = (hash * 31 + char.charCodeAt(0)) % 360;
  return hash;
}

export function productMockupSvg(drop: Drop, product: Product): string {
  const hue = hueFrom(`${drop.brandName}:${product.name}`);
  const accent = `hsl(${hue} 88% 62%)`;
  const gold = `hsl(${(hue + 58) % 360} 86% 74%)`;
  const deep = `hsl(${(hue + 226) % 360} 70% 8%)`;
  const name = escapeXml(product.name);
  const type = escapeXml(product.type.toUpperCase());
  const brand = escapeXml(drop.brandName);

  return `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900" viewBox="0 0 900 900">
  <defs>
    <radialGradient id="glow" cx="50%" cy="34%" r="68%">
      <stop offset="0" stop-color="${accent}" stop-opacity=".48"/>
      <stop offset=".52" stop-color="${deep}" stop-opacity=".96"/>
      <stop offset="1" stop-color="#020207"/>
    </radialGradient>
    <linearGradient id="cloth" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#202033"/>
      <stop offset="1" stop-color="#06060d"/>
    </linearGradient>
  </defs>
  <rect width="900" height="900" fill="url(#glow)"/>
  <circle cx="450" cy="302" r="190" fill="none" stroke="${gold}" stroke-width="7" opacity=".9"/>
  <circle cx="450" cy="302" r="150" fill="none" stroke="${accent}" stroke-width="2" opacity=".65"/>
  <path d="M242 236h416l72 116-88 68v282H258V420l-88-68 72-116z" fill="url(#cloth)" stroke="rgba(255,255,255,.5)" stroke-width="5" stroke-linejoin="round"/>
  <path d="M332 236c18 62 57 94 118 94s100-32 118-94" fill="none" stroke="rgba(255,255,255,.45)" stroke-width="6"/>
  <circle cx="450" cy="478" r="66" fill="none" stroke="${gold}" stroke-width="5"/>
  <circle cx="450" cy="478" r="34" fill="${accent}"/>
  <text x="450" y="646" text-anchor="middle" font-family="Georgia, 'Times New Roman', serif" font-size="36" fill="#fff2d5">${name}</text>
  <text x="450" y="704" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="22" font-weight="800" fill="${gold}">${brand} / ${type}</text>
  <text x="450" y="792" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="18" font-weight="700" fill="rgba(255,242,213,.58)">generated by DropLink</text>
</svg>`;
}
